"""Add SearchHistory model and update User model

Revision ID: 1cc38efb55c8
Revises: 1a9cae533f24
Create Date: 2024-08-07 12:31:40.654987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc38efb55c8'
down_revision = '1a9cae533f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, alter the 'users' table to add the 'spotify_user_id' column
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_user_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['spotify_user_id'])

    # Then, create the 'search_history' table
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('spotify_link', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_user_id'], ['users.spotify_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the 'search_history' table first
    op.drop_table('search_history')

    # Then, alter the 'users' table to remove the 'spotify_user_id' column
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('spotify_user_id')
    # ### end Alembic commands ###
