"""Initial migration: user and openai_response models

Revision ID: 840e229bbbf6
Revises: 
Create Date: 2024-07-22 15:18:57.847600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840e229bbbf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('openai_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('songs', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['users.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openai_responses')
    op.drop_table('users')
    # ### end Alembic commands ###
