"""Adjust foreign key constraints for spotify_user_id

Revision ID: 9489f81dc97b
Revises: 35552330f892
Create Date: 2024-08-07 23:37:20.742005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9489f81dc97b'
down_revision = '35552330f892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_constraint('search_history_spotify_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_spotify_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_spotify_user_id_key', ['spotify_user_id'])

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_foreign_key('search_history_spotify_user_id_fkey', 'users', ['spotify_user_id'], ['spotify_user_id'])

    # ### end Alembic commands ###
